### ISSUE TITLE
Bullet points under Introductions do not display properly on Connect

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NSAWTraining/Rpkgs#11]
The bullet points under the [Introductions](https://connect.fisheries.noaa.gov/developing-r-packages/developing_rpkgs.html#introductions) section do not display properly on Connect. I can confirm that they look fine when rendering the .qmd file on my local machine.

**Comment by k-doering-NOAA** [comment]
I think the Connect version of the doc is older :( There is a bug with the version of connect we are using that prevents it from auto updating from git all the time (it will be fixed when we update connect in 2 weeks).

So, I think it is best to treat your local version as the "right" one, and I'll make a note to manually update the connect version once we have stopped editing!
